ALTER TABLE scada_turbina1_all
  ADD COLUMN IF NOT EXISTS deltaT_aire DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS dev_avg DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS anomaly_score DOUBLE PRECISION;

